### ISSUE TITLE
Dangerously set inner html?

### ISSUE THREAD

**Issue by bcomnes** [WebReflection/uhtml-ssr#3]
Say I have a string of html generated by some other trusted source and I want to dangerously set it as the innerText of a node in a uhtml-ssr template (from a variable for example). Is that possible somehow?

```js
import {render, html, svg} from 'uhtml-ssr';

const someHtml = '<div>hello world</div>'

// What's the right way to do this without escaping?
const output = render(String, html`<div>
Hello µhtml-ssr
<div>${someHtml}</div>
</div>`);
```

**Comment by WebReflection** [comment]
Use the tag as function, passing an array, instead of a static template, as first argument:

```js
const output = render(String, html`<div>
Hello µhtml-ssr
<div>${html([someHtml])}</div>
</div>`);
```

This will be processed each time, no cache whatsoever, but for SSR it shouldn't be an issue, in terms of performance, so that's it.

**Comment by bcomnes** [comment]
Yeah i'm using it for a simple static site build and want to source some inner html from markdown. The performance shouldn't be an issue

**Comment by harnyk** [comment]
@bcomnes 
Or alternatively you can do it lake this:

```ts
import { Hole, html, render } from "uhtml-ssr"

const output = render(String, html`<div>
Hello µhtml-ssr
<div>${new Hole(someHtml)}</div>
</div>`);

```

**Comment by bcomnes** [comment]
Nice!
